import time
from datetime import datetime
from pathlib import Path

from sqlalchemy.orm import sessionmaker

from ..models import MediaFile, ProcessingStatusEnum
from ..settings import Settings


def _simulate_whisperx_generate_srt(media_path: str, out_srt_path: str, settings: Settings):
    """
    Placeholder for WhisperX integration.
    In a real environment, call WhisperX APIs/library to transcribe and align subtitles.
    Here, we simulate processing delay and generate a tiny SRT file for demonstration.
    """
    # Simulate processing latency
    time.sleep(2)

    content = """1
00:00:00,000 --> 00:00:02,000
Hello, this is a simulated subtitle.

2
00:00:02,000 --> 00:00:04,000
Generated by the WhisperX processing stub.
"""
    Path(out_srt_path).write_text(content, encoding="utf-8")


def process_media_with_whisperx(
    media_id: str,
    media_path: str,
    subtitle_dir: str,
    db_maker: sessionmaker,
    settings: Settings,
):
    """
    Background task: update status to PROCESSING, invoke WhisperX to generate SRT,
    store subtitle path, set COMPLETED, or FAILED on error.
    """
    db = db_maker()
    try:
        media = db.get(MediaFile, media_id)
        if not media:
            return

        media.status = ProcessingStatusEnum.PROCESSING
        media.updated_at = datetime.utcnow()
        db.add(media)
        db.commit()

        subtitle_out_path = str(Path(subtitle_dir) / f"{media_id}.srt")
        _simulate_whisperx_generate_srt(media_path=media_path, out_srt_path=subtitle_out_path, settings=settings)

        media.subtitle_path = subtitle_out_path
        media.status = ProcessingStatusEnum.COMPLETED
        media.updated_at = datetime.utcnow()
        db.add(media)
        db.commit()
    except Exception as e:
        db.rollback()
        try:
            media = db.get(MediaFile, media_id)
            if media:
                media.status = ProcessingStatusEnum.FAILED
                media.error_message = str(e)
                media.updated_at = datetime.utcnow()
                db.add(media)
                db.commit()
        except Exception:
            db.rollback()
    finally:
        db.close()
